Wrapper user implementation
HoloPanio/duxcore pull request #34
Opened 2021-11-08 20:01 UTC by TheOtterlord

Implements remaining user routes & replaces axios usage with wrapper usage.

2021-11-08 20:04 UTC, overlisted approved these changes
lgtm 😎

2021-11-08 20:04 UTC, HoloPanio commented
could you replace all the resources that are provided by the wrapper in the dashboard.  Also commitlint

2021-11-08 20:06 UTC, goldyydev commented on dashboard/src/context/WrapperProvider.tsx
> +export const useWrapper = () => useContext(WrapperContext);
```suggestion
export const useWrapper = () => useContext(WrapperContext);

```
newline :(

2021-11-08 20:06 UTC, TheOtterlord commented
> could you replace all the resources that are provided by the wrapper in the dashboard
Like what?

> Also commitlint
lol, even when I use the command it breaks

2021-11-08 20:07 UTC, goldyydev approved these changes

2021-11-09 15:05 UTC, HoloPanio requested changes
Go ahead and take a look at these comments when you get the chance

2021-11-09 15:05 UTC, HoloPanio commented on dashboard/src/modules/auth/AuthProvider.tsx
> +import { User } from "@duxcore/wrapper/lib/types/user";
Have the wrapper export the types in the index file if you could

2021-11-09 15:05 UTC, HoloPanio commented on dashboard/src/modules/auth/login/LoginForm.tsx
> +import type { TokenPair } from "@duxcore/wrapper/lib/types/user";
Again move the types to the wrapper index

2021-11-09 15:05 UTC, HoloPanio commented on dashboard/src/modules/auth/AuthProvider.tsx
>  import { useTokenStore } from "./useTokenStore";
change the useTokenStore and useHasToken to the wrapper varients throughout the entire dashboard.

2021-11-09 15:05 UTC, HoloPanio commented on dashboard/src/modules/auth/login/LoginPage.tsx
>  import { useHasToken } from "../useHasToken";
port from wrapper please

2021-11-09 15:05 UTC, HoloPanio commented on dashboard/src/modules/auth/login/LoginPage.tsx
> +import type { TokenPair } from "@duxcore/wrapper/lib/types/user";
export types to index file

2021-11-10 14:57 UTC, HoloPanio approved these changes
Thanks for being so receptive with the changes that I have requested, I appreciate this very much because now we can streamline the wrapper.  I'll go ahead and push this through for you!

---

Jackson R.
Project Manager and Lead Backend Developer

2021-11-10 14:58 UTC, merged