page to view and create projects
HoloPanio/duxcore pull request #93
Opened 2022-12-08 17:09 UTC by amitojsingh366

2022-12-09 23:01 UTC, TheOtterlord commented
This looks sick. I do have one major thing to note however. The user won't be creating services using the current endpoint unless their administrator (I forgot to mention this sry). so the current service creation page should probably be restricted to admins or rewritten for the future, as once we define our first service, we'll probably need a general service form page that can fill in with required fields. It might still be worth keeping the current one though, as a hard coded page just for admins.

thoughts? @HoloPanio

2022-12-09 23:15 UTC, HoloPanio commented
I already informed him of the admin only condition of the route, but it would've had to been changed regardless.

As far as quality of life, @amitojsingh366 can you make the params field a bit bigger for readability's sake?

2022-12-10 04:52 UTC, HoloPanio commented
Also this looks amazing, I love it a lot

2022-12-10 10:37 UTC, amitojsingh366 commented
> As far as quality of life, @amitojsingh366 can you make the params field a bit bigger for readability's sake?

@HoloPanio you want the params field on the create service page to be bigger, correct?

2022-12-10 12:12 UTC, amitojsingh366 commented
@HoloPanio I am now using a text area for the params field on create service page, this allows the user to resize it as they wish. screenshot updated.

2022-12-10 13:43 UTC, goldyydev requested changes

2022-12-10 13:43 UTC, goldyydev commented on dashboard/package.json
> +    "moment": "^2.29.4",
[Do we really need momentjs?](https://you-dont-need.github.io/You-Dont-Need-Momentjs/)

2022-12-10 13:43 UTC, goldyydev commented on dashboard/src/modules/services/ViewServicePage.tsx
> +              <p>Created: {moment(serviceData?.createdAt).format('MMMM Do YYYY, h:mm:ss a')}</p>
Might be worth it to use Intl.DateTimeFormat instead.

2022-12-10 15:11 UTC, goldyydev commented on dashboard/src/modules/services/ViewServicePage.tsx
> +              <p>Created: {moment(serviceData?.createdAt).format('MMMM Do YYYY, h:mm:ss a')}</p>
Or dayjs

2022-12-12 12:46 UTC, goldyydev approved these changes

2022-12-12 13:05 UTC, TheOtterlord approved these changes

2022-12-12 16:56 UTC, merged